apiVersion: v2
name: my-app
description: Sample consumer app using sample-lib
version: 0.1.0

dependencies:
  - name: sample-lib
    version: 0.1.0
    repository:  https://idletekz.github.io/sample-lib
